name: CI Run Python Tests
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *"
run-name: Running tests for Python CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8" # install the python version needed

      - name: Install Dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"

      - name: Run Tests # run main.py
        run: python -m unittest tests/test_urls.py
